// @generated
//
// whisper.cpp FFI surface — produced by bindgen against the
// submodule pinned at `crates/whisper-cpp/whisper.cpp/`. Do
// not edit by hand: every `cargo build` regenerates this
// file from `wrapper.h` and the allowlist in `build.rs`.
//
// Adding a new symbol means extending BOTH `wrapper.h`'s
// `#include` set AND the `allowlist_*` directives in
// `build.rs::generate_bindings()`. Do not relax the
// allowlists casually — they are the boundary between
// "FFI surface we own" and "every header bindgen could
// possibly pull in transitively."
//
// Source crate: whisper-cpp 0.0.1
// Source header: wrapper.h -> whisper.cpp/include/whisper.h
//

/* automatically generated by rust-bindgen 0.72.1 */

pub const WHISPER_SAMPLE_RATE: u32 = 16000;
pub const WHISPER_N_FFT: u32 = 400;
pub const WHISPER_HOP_LENGTH: u32 = 160;
pub const WHISPER_CHUNK_SIZE: u32 = 30;
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct ggml_context {
  _unused: [u8; 0],
}
pub const ggml_type_GGML_TYPE_F32: ggml_type = 0;
pub const ggml_type_GGML_TYPE_F16: ggml_type = 1;
pub const ggml_type_GGML_TYPE_Q4_0: ggml_type = 2;
pub const ggml_type_GGML_TYPE_Q4_1: ggml_type = 3;
pub const ggml_type_GGML_TYPE_Q5_0: ggml_type = 6;
pub const ggml_type_GGML_TYPE_Q5_1: ggml_type = 7;
pub const ggml_type_GGML_TYPE_Q8_0: ggml_type = 8;
pub const ggml_type_GGML_TYPE_Q8_1: ggml_type = 9;
pub const ggml_type_GGML_TYPE_Q2_K: ggml_type = 10;
pub const ggml_type_GGML_TYPE_Q3_K: ggml_type = 11;
pub const ggml_type_GGML_TYPE_Q4_K: ggml_type = 12;
pub const ggml_type_GGML_TYPE_Q5_K: ggml_type = 13;
pub const ggml_type_GGML_TYPE_Q6_K: ggml_type = 14;
pub const ggml_type_GGML_TYPE_Q8_K: ggml_type = 15;
pub const ggml_type_GGML_TYPE_IQ2_XXS: ggml_type = 16;
pub const ggml_type_GGML_TYPE_IQ2_XS: ggml_type = 17;
pub const ggml_type_GGML_TYPE_IQ3_XXS: ggml_type = 18;
pub const ggml_type_GGML_TYPE_IQ1_S: ggml_type = 19;
pub const ggml_type_GGML_TYPE_IQ4_NL: ggml_type = 20;
pub const ggml_type_GGML_TYPE_IQ3_S: ggml_type = 21;
pub const ggml_type_GGML_TYPE_IQ2_S: ggml_type = 22;
pub const ggml_type_GGML_TYPE_IQ4_XS: ggml_type = 23;
pub const ggml_type_GGML_TYPE_I8: ggml_type = 24;
pub const ggml_type_GGML_TYPE_I16: ggml_type = 25;
pub const ggml_type_GGML_TYPE_I32: ggml_type = 26;
pub const ggml_type_GGML_TYPE_I64: ggml_type = 27;
pub const ggml_type_GGML_TYPE_F64: ggml_type = 28;
pub const ggml_type_GGML_TYPE_IQ1_M: ggml_type = 29;
pub const ggml_type_GGML_TYPE_BF16: ggml_type = 30;
pub const ggml_type_GGML_TYPE_TQ1_0: ggml_type = 34;
pub const ggml_type_GGML_TYPE_TQ2_0: ggml_type = 35;
pub const ggml_type_GGML_TYPE_MXFP4: ggml_type = 39;
pub const ggml_type_GGML_TYPE_NVFP4: ggml_type = 40;
pub const ggml_type_GGML_TYPE_COUNT: ggml_type = 41;
pub type ggml_type = ::std::os::raw::c_uint;
pub const ggml_op_GGML_OP_NONE: ggml_op = 0;
pub const ggml_op_GGML_OP_DUP: ggml_op = 1;
pub const ggml_op_GGML_OP_ADD: ggml_op = 2;
pub const ggml_op_GGML_OP_ADD_ID: ggml_op = 3;
pub const ggml_op_GGML_OP_ADD1: ggml_op = 4;
pub const ggml_op_GGML_OP_ACC: ggml_op = 5;
pub const ggml_op_GGML_OP_SUB: ggml_op = 6;
pub const ggml_op_GGML_OP_MUL: ggml_op = 7;
pub const ggml_op_GGML_OP_DIV: ggml_op = 8;
pub const ggml_op_GGML_OP_SQR: ggml_op = 9;
pub const ggml_op_GGML_OP_SQRT: ggml_op = 10;
pub const ggml_op_GGML_OP_LOG: ggml_op = 11;
pub const ggml_op_GGML_OP_SIN: ggml_op = 12;
pub const ggml_op_GGML_OP_COS: ggml_op = 13;
pub const ggml_op_GGML_OP_SUM: ggml_op = 14;
pub const ggml_op_GGML_OP_SUM_ROWS: ggml_op = 15;
pub const ggml_op_GGML_OP_CUMSUM: ggml_op = 16;
pub const ggml_op_GGML_OP_MEAN: ggml_op = 17;
pub const ggml_op_GGML_OP_ARGMAX: ggml_op = 18;
pub const ggml_op_GGML_OP_COUNT_EQUAL: ggml_op = 19;
pub const ggml_op_GGML_OP_REPEAT: ggml_op = 20;
pub const ggml_op_GGML_OP_REPEAT_BACK: ggml_op = 21;
pub const ggml_op_GGML_OP_CONCAT: ggml_op = 22;
pub const ggml_op_GGML_OP_SILU_BACK: ggml_op = 23;
pub const ggml_op_GGML_OP_NORM: ggml_op = 24;
pub const ggml_op_GGML_OP_RMS_NORM: ggml_op = 25;
pub const ggml_op_GGML_OP_RMS_NORM_BACK: ggml_op = 26;
pub const ggml_op_GGML_OP_GROUP_NORM: ggml_op = 27;
pub const ggml_op_GGML_OP_L2_NORM: ggml_op = 28;
pub const ggml_op_GGML_OP_MUL_MAT: ggml_op = 29;
pub const ggml_op_GGML_OP_MUL_MAT_ID: ggml_op = 30;
pub const ggml_op_GGML_OP_OUT_PROD: ggml_op = 31;
pub const ggml_op_GGML_OP_SCALE: ggml_op = 32;
pub const ggml_op_GGML_OP_SET: ggml_op = 33;
pub const ggml_op_GGML_OP_CPY: ggml_op = 34;
pub const ggml_op_GGML_OP_CONT: ggml_op = 35;
pub const ggml_op_GGML_OP_RESHAPE: ggml_op = 36;
pub const ggml_op_GGML_OP_VIEW: ggml_op = 37;
pub const ggml_op_GGML_OP_PERMUTE: ggml_op = 38;
pub const ggml_op_GGML_OP_TRANSPOSE: ggml_op = 39;
pub const ggml_op_GGML_OP_GET_ROWS: ggml_op = 40;
pub const ggml_op_GGML_OP_GET_ROWS_BACK: ggml_op = 41;
pub const ggml_op_GGML_OP_SET_ROWS: ggml_op = 42;
pub const ggml_op_GGML_OP_DIAG: ggml_op = 43;
pub const ggml_op_GGML_OP_DIAG_MASK_INF: ggml_op = 44;
pub const ggml_op_GGML_OP_DIAG_MASK_ZERO: ggml_op = 45;
pub const ggml_op_GGML_OP_SOFT_MAX: ggml_op = 46;
pub const ggml_op_GGML_OP_SOFT_MAX_BACK: ggml_op = 47;
pub const ggml_op_GGML_OP_ROPE: ggml_op = 48;
pub const ggml_op_GGML_OP_ROPE_BACK: ggml_op = 49;
pub const ggml_op_GGML_OP_CLAMP: ggml_op = 50;
pub const ggml_op_GGML_OP_CONV_TRANSPOSE_1D: ggml_op = 51;
pub const ggml_op_GGML_OP_IM2COL: ggml_op = 52;
pub const ggml_op_GGML_OP_IM2COL_BACK: ggml_op = 53;
pub const ggml_op_GGML_OP_IM2COL_3D: ggml_op = 54;
pub const ggml_op_GGML_OP_CONV_2D: ggml_op = 55;
pub const ggml_op_GGML_OP_CONV_3D: ggml_op = 56;
pub const ggml_op_GGML_OP_CONV_2D_DW: ggml_op = 57;
pub const ggml_op_GGML_OP_CONV_TRANSPOSE_2D: ggml_op = 58;
pub const ggml_op_GGML_OP_POOL_1D: ggml_op = 59;
pub const ggml_op_GGML_OP_POOL_2D: ggml_op = 60;
pub const ggml_op_GGML_OP_POOL_2D_BACK: ggml_op = 61;
pub const ggml_op_GGML_OP_UPSCALE: ggml_op = 62;
pub const ggml_op_GGML_OP_PAD: ggml_op = 63;
pub const ggml_op_GGML_OP_PAD_REFLECT_1D: ggml_op = 64;
pub const ggml_op_GGML_OP_ROLL: ggml_op = 65;
pub const ggml_op_GGML_OP_ARANGE: ggml_op = 66;
pub const ggml_op_GGML_OP_TIMESTEP_EMBEDDING: ggml_op = 67;
pub const ggml_op_GGML_OP_ARGSORT: ggml_op = 68;
pub const ggml_op_GGML_OP_TOP_K: ggml_op = 69;
pub const ggml_op_GGML_OP_LEAKY_RELU: ggml_op = 70;
pub const ggml_op_GGML_OP_TRI: ggml_op = 71;
pub const ggml_op_GGML_OP_FILL: ggml_op = 72;
pub const ggml_op_GGML_OP_FLASH_ATTN_EXT: ggml_op = 73;
pub const ggml_op_GGML_OP_FLASH_ATTN_BACK: ggml_op = 74;
pub const ggml_op_GGML_OP_SSM_CONV: ggml_op = 75;
pub const ggml_op_GGML_OP_SSM_SCAN: ggml_op = 76;
pub const ggml_op_GGML_OP_WIN_PART: ggml_op = 77;
pub const ggml_op_GGML_OP_WIN_UNPART: ggml_op = 78;
pub const ggml_op_GGML_OP_GET_REL_POS: ggml_op = 79;
pub const ggml_op_GGML_OP_ADD_REL_POS: ggml_op = 80;
pub const ggml_op_GGML_OP_RWKV_WKV6: ggml_op = 81;
pub const ggml_op_GGML_OP_GATED_LINEAR_ATTN: ggml_op = 82;
pub const ggml_op_GGML_OP_RWKV_WKV7: ggml_op = 83;
pub const ggml_op_GGML_OP_SOLVE_TRI: ggml_op = 84;
pub const ggml_op_GGML_OP_GATED_DELTA_NET: ggml_op = 85;
pub const ggml_op_GGML_OP_UNARY: ggml_op = 86;
pub const ggml_op_GGML_OP_MAP_CUSTOM1: ggml_op = 87;
pub const ggml_op_GGML_OP_MAP_CUSTOM2: ggml_op = 88;
pub const ggml_op_GGML_OP_MAP_CUSTOM3: ggml_op = 89;
pub const ggml_op_GGML_OP_CUSTOM: ggml_op = 90;
pub const ggml_op_GGML_OP_CROSS_ENTROPY_LOSS: ggml_op = 91;
pub const ggml_op_GGML_OP_CROSS_ENTROPY_LOSS_BACK: ggml_op = 92;
pub const ggml_op_GGML_OP_OPT_STEP_ADAMW: ggml_op = 93;
pub const ggml_op_GGML_OP_OPT_STEP_SGD: ggml_op = 94;
pub const ggml_op_GGML_OP_GLU: ggml_op = 95;
pub const ggml_op_GGML_OP_COUNT: ggml_op = 96;
pub type ggml_op = ::std::os::raw::c_uint;
pub const ggml_log_level_GGML_LOG_LEVEL_NONE: ggml_log_level = 0;
pub const ggml_log_level_GGML_LOG_LEVEL_DEBUG: ggml_log_level = 1;
pub const ggml_log_level_GGML_LOG_LEVEL_INFO: ggml_log_level = 2;
pub const ggml_log_level_GGML_LOG_LEVEL_WARN: ggml_log_level = 3;
pub const ggml_log_level_GGML_LOG_LEVEL_ERROR: ggml_log_level = 4;
pub const ggml_log_level_GGML_LOG_LEVEL_CONT: ggml_log_level = 5;
pub type ggml_log_level = ::std::os::raw::c_uint;
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct ggml_tensor {
  pub type_: ggml_type,
  pub buffer: *mut ggml_backend_buffer,
  pub ne: [i64; 4usize],
  pub nb: [usize; 4usize],
  pub op: ggml_op,
  pub op_params: [i32; 16usize],
  pub flags: i32,
  pub src: [*mut ggml_tensor; 10usize],
  pub view_src: *mut ggml_tensor,
  pub view_offs: usize,
  pub data: *mut ::std::os::raw::c_void,
  pub name: [::std::os::raw::c_char; 64usize],
  pub extra: *mut ::std::os::raw::c_void,
  pub padding: [::std::os::raw::c_char; 8usize],
}
impl Default for ggml_tensor {
  fn default() -> Self {
    let mut s = ::std::mem::MaybeUninit::<Self>::uninit();
    unsafe {
      ::std::ptr::write_bytes(s.as_mut_ptr(), 0, 1);
      s.assume_init()
    }
  }
}
pub type ggml_abort_callback =
  ::std::option::Option<unsafe extern "C" fn(data: *mut ::std::os::raw::c_void) -> bool>;
unsafe extern "C" {
  pub fn ggml_log_inplace(ctx: *mut ggml_context, a: *mut ggml_tensor) -> *mut ggml_tensor;
}
pub type ggml_log_callback = ::std::option::Option<
  unsafe extern "C" fn(
    level: ggml_log_level,
    text: *const ::std::os::raw::c_char,
    user_data: *mut ::std::os::raw::c_void,
  ),
>;
unsafe extern "C" {
  pub fn ggml_log_get(
    log_callback: *mut ggml_log_callback,
    user_data: *mut *mut ::std::os::raw::c_void,
  );
}
unsafe extern "C" {
  pub fn ggml_log_set(log_callback: ggml_log_callback, user_data: *mut ::std::os::raw::c_void);
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct whisper_context {
  _unused: [u8; 0],
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct whisper_state {
  _unused: [u8; 0],
}
pub type whisper_pos = i32;
pub type whisper_token = i32;
pub type whisper_seq_id = i32;
pub const whisper_alignment_heads_preset_WHISPER_AHEADS_NONE: whisper_alignment_heads_preset = 0;
pub const whisper_alignment_heads_preset_WHISPER_AHEADS_N_TOP_MOST: whisper_alignment_heads_preset =
  1;
pub const whisper_alignment_heads_preset_WHISPER_AHEADS_CUSTOM: whisper_alignment_heads_preset = 2;
pub const whisper_alignment_heads_preset_WHISPER_AHEADS_TINY_EN: whisper_alignment_heads_preset = 3;
pub const whisper_alignment_heads_preset_WHISPER_AHEADS_TINY: whisper_alignment_heads_preset = 4;
pub const whisper_alignment_heads_preset_WHISPER_AHEADS_BASE_EN: whisper_alignment_heads_preset = 5;
pub const whisper_alignment_heads_preset_WHISPER_AHEADS_BASE: whisper_alignment_heads_preset = 6;
pub const whisper_alignment_heads_preset_WHISPER_AHEADS_SMALL_EN: whisper_alignment_heads_preset =
  7;
pub const whisper_alignment_heads_preset_WHISPER_AHEADS_SMALL: whisper_alignment_heads_preset = 8;
pub const whisper_alignment_heads_preset_WHISPER_AHEADS_MEDIUM_EN: whisper_alignment_heads_preset =
  9;
pub const whisper_alignment_heads_preset_WHISPER_AHEADS_MEDIUM: whisper_alignment_heads_preset = 10;
pub const whisper_alignment_heads_preset_WHISPER_AHEADS_LARGE_V1: whisper_alignment_heads_preset =
  11;
pub const whisper_alignment_heads_preset_WHISPER_AHEADS_LARGE_V2: whisper_alignment_heads_preset =
  12;
pub const whisper_alignment_heads_preset_WHISPER_AHEADS_LARGE_V3: whisper_alignment_heads_preset =
  13;
pub const whisper_alignment_heads_preset_WHISPER_AHEADS_LARGE_V3_TURBO:
  whisper_alignment_heads_preset = 14;
pub type whisper_alignment_heads_preset = ::std::os::raw::c_uint;
#[repr(C)]
#[derive(Debug, Default, Copy, Clone)]
pub struct whisper_ahead {
  pub n_text_layer: ::std::os::raw::c_int,
  pub n_head: ::std::os::raw::c_int,
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct whisper_aheads {
  pub n_heads: usize,
  pub heads: *const whisper_ahead,
}
impl Default for whisper_aheads {
  fn default() -> Self {
    let mut s = ::std::mem::MaybeUninit::<Self>::uninit();
    unsafe {
      ::std::ptr::write_bytes(s.as_mut_ptr(), 0, 1);
      s.assume_init()
    }
  }
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct whisper_context_params {
  pub use_gpu: bool,
  pub flash_attn: bool,
  pub gpu_device: ::std::os::raw::c_int,
  pub dtw_token_timestamps: bool,
  pub dtw_aheads_preset: whisper_alignment_heads_preset,
  pub dtw_n_top: ::std::os::raw::c_int,
  pub dtw_aheads: whisper_aheads,
  pub dtw_mem_size: usize,
}
impl Default for whisper_context_params {
  fn default() -> Self {
    let mut s = ::std::mem::MaybeUninit::<Self>::uninit();
    unsafe {
      ::std::ptr::write_bytes(s.as_mut_ptr(), 0, 1);
      s.assume_init()
    }
  }
}
#[repr(C)]
#[derive(Debug, Default, Copy, Clone)]
pub struct whisper_token_data {
  pub id: whisper_token,
  pub tid: whisper_token,
  pub p: f32,
  pub plog: f32,
  pub pt: f32,
  pub ptsum: f32,
  pub t0: i64,
  pub t1: i64,
  pub t_dtw: i64,
  pub vlen: f32,
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct whisper_model_loader {
  pub context: *mut ::std::os::raw::c_void,
  pub read: ::std::option::Option<
    unsafe extern "C" fn(
      ctx: *mut ::std::os::raw::c_void,
      output: *mut ::std::os::raw::c_void,
      read_size: usize,
    ) -> usize,
  >,
  pub eof: ::std::option::Option<unsafe extern "C" fn(ctx: *mut ::std::os::raw::c_void) -> bool>,
  pub close: ::std::option::Option<unsafe extern "C" fn(ctx: *mut ::std::os::raw::c_void)>,
}
impl Default for whisper_model_loader {
  fn default() -> Self {
    let mut s = ::std::mem::MaybeUninit::<Self>::uninit();
    unsafe {
      ::std::ptr::write_bytes(s.as_mut_ptr(), 0, 1);
      s.assume_init()
    }
  }
}
pub const whisper_gretype_WHISPER_GRETYPE_END: whisper_gretype = 0;
pub const whisper_gretype_WHISPER_GRETYPE_ALT: whisper_gretype = 1;
pub const whisper_gretype_WHISPER_GRETYPE_RULE_REF: whisper_gretype = 2;
pub const whisper_gretype_WHISPER_GRETYPE_CHAR: whisper_gretype = 3;
pub const whisper_gretype_WHISPER_GRETYPE_CHAR_NOT: whisper_gretype = 4;
pub const whisper_gretype_WHISPER_GRETYPE_CHAR_RNG_UPPER: whisper_gretype = 5;
pub const whisper_gretype_WHISPER_GRETYPE_CHAR_ALT: whisper_gretype = 6;
pub type whisper_gretype = ::std::os::raw::c_uint;
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct whisper_grammar_element {
  pub type_: whisper_gretype,
  pub value: u32,
}
impl Default for whisper_grammar_element {
  fn default() -> Self {
    let mut s = ::std::mem::MaybeUninit::<Self>::uninit();
    unsafe {
      ::std::ptr::write_bytes(s.as_mut_ptr(), 0, 1);
      s.assume_init()
    }
  }
}
#[repr(C)]
#[derive(Debug, Default, Copy, Clone)]
pub struct whisper_vad_params {
  pub threshold: f32,
  pub min_speech_duration_ms: ::std::os::raw::c_int,
  pub min_silence_duration_ms: ::std::os::raw::c_int,
  pub max_speech_duration_s: f32,
  pub speech_pad_ms: ::std::os::raw::c_int,
  pub samples_overlap: f32,
}
unsafe extern "C" {
  pub fn whisper_version() -> *const ::std::os::raw::c_char;
}
unsafe extern "C" {
  pub fn whisper_init_from_file_with_params(
    path_model: *const ::std::os::raw::c_char,
    params: whisper_context_params,
  ) -> *mut whisper_context;
}
unsafe extern "C" {
  pub fn whisper_init_from_buffer_with_params(
    buffer: *mut ::std::os::raw::c_void,
    buffer_size: usize,
    params: whisper_context_params,
  ) -> *mut whisper_context;
}
unsafe extern "C" {
  pub fn whisper_init_with_params(
    loader: *mut whisper_model_loader,
    params: whisper_context_params,
  ) -> *mut whisper_context;
}
unsafe extern "C" {
  pub fn whisper_init_from_file_with_params_no_state(
    path_model: *const ::std::os::raw::c_char,
    params: whisper_context_params,
  ) -> *mut whisper_context;
}
unsafe extern "C" {
  pub fn whisper_init_from_buffer_with_params_no_state(
    buffer: *mut ::std::os::raw::c_void,
    buffer_size: usize,
    params: whisper_context_params,
  ) -> *mut whisper_context;
}
unsafe extern "C" {
  pub fn whisper_init_with_params_no_state(
    loader: *mut whisper_model_loader,
    params: whisper_context_params,
  ) -> *mut whisper_context;
}
unsafe extern "C" {
  pub fn whisper_init_from_file(path_model: *const ::std::os::raw::c_char) -> *mut whisper_context;
}
unsafe extern "C" {
  pub fn whisper_init_from_buffer(
    buffer: *mut ::std::os::raw::c_void,
    buffer_size: usize,
  ) -> *mut whisper_context;
}
unsafe extern "C" {
  pub fn whisper_init(loader: *mut whisper_model_loader) -> *mut whisper_context;
}
unsafe extern "C" {
  pub fn whisper_init_from_file_no_state(
    path_model: *const ::std::os::raw::c_char,
  ) -> *mut whisper_context;
}
unsafe extern "C" {
  pub fn whisper_init_from_buffer_no_state(
    buffer: *mut ::std::os::raw::c_void,
    buffer_size: usize,
  ) -> *mut whisper_context;
}
unsafe extern "C" {
  pub fn whisper_init_no_state(loader: *mut whisper_model_loader) -> *mut whisper_context;
}
unsafe extern "C" {
  pub fn whisper_init_state(ctx: *mut whisper_context) -> *mut whisper_state;
}
unsafe extern "C" {
  pub fn whisper_ctx_init_openvino_encoder_with_state(
    ctx: *mut whisper_context,
    state: *mut whisper_state,
    model_path: *const ::std::os::raw::c_char,
    device: *const ::std::os::raw::c_char,
    cache_dir: *const ::std::os::raw::c_char,
  ) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
  pub fn whisper_ctx_init_openvino_encoder(
    ctx: *mut whisper_context,
    model_path: *const ::std::os::raw::c_char,
    device: *const ::std::os::raw::c_char,
    cache_dir: *const ::std::os::raw::c_char,
  ) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
  pub fn whisper_free(ctx: *mut whisper_context);
}
unsafe extern "C" {
  pub fn whisper_free_state(state: *mut whisper_state);
}
unsafe extern "C" {
  pub fn whisper_free_params(params: *mut whisper_full_params);
}
unsafe extern "C" {
  pub fn whisper_free_context_params(params: *mut whisper_context_params);
}
unsafe extern "C" {
  pub fn whisper_pcm_to_mel(
    ctx: *mut whisper_context,
    samples: *const f32,
    n_samples: ::std::os::raw::c_int,
    n_threads: ::std::os::raw::c_int,
  ) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
  pub fn whisper_pcm_to_mel_with_state(
    ctx: *mut whisper_context,
    state: *mut whisper_state,
    samples: *const f32,
    n_samples: ::std::os::raw::c_int,
    n_threads: ::std::os::raw::c_int,
  ) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
  pub fn whisper_set_mel(
    ctx: *mut whisper_context,
    data: *const f32,
    n_len: ::std::os::raw::c_int,
    n_mel: ::std::os::raw::c_int,
  ) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
  pub fn whisper_set_mel_with_state(
    ctx: *mut whisper_context,
    state: *mut whisper_state,
    data: *const f32,
    n_len: ::std::os::raw::c_int,
    n_mel: ::std::os::raw::c_int,
  ) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
  pub fn whisper_encode(
    ctx: *mut whisper_context,
    offset: ::std::os::raw::c_int,
    n_threads: ::std::os::raw::c_int,
  ) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
  pub fn whisper_encode_with_state(
    ctx: *mut whisper_context,
    state: *mut whisper_state,
    offset: ::std::os::raw::c_int,
    n_threads: ::std::os::raw::c_int,
  ) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
  pub fn whisper_decode(
    ctx: *mut whisper_context,
    tokens: *const whisper_token,
    n_tokens: ::std::os::raw::c_int,
    n_past: ::std::os::raw::c_int,
    n_threads: ::std::os::raw::c_int,
  ) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
  pub fn whisper_decode_with_state(
    ctx: *mut whisper_context,
    state: *mut whisper_state,
    tokens: *const whisper_token,
    n_tokens: ::std::os::raw::c_int,
    n_past: ::std::os::raw::c_int,
    n_threads: ::std::os::raw::c_int,
  ) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
  pub fn whisper_tokenize(
    ctx: *mut whisper_context,
    text: *const ::std::os::raw::c_char,
    tokens: *mut whisper_token,
    n_max_tokens: ::std::os::raw::c_int,
  ) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
  pub fn whisper_token_count(
    ctx: *mut whisper_context,
    text: *const ::std::os::raw::c_char,
  ) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
  pub fn whisper_lang_max_id() -> ::std::os::raw::c_int;
}
unsafe extern "C" {
  pub fn whisper_lang_id(lang: *const ::std::os::raw::c_char) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
  pub fn whisper_lang_str(id: ::std::os::raw::c_int) -> *const ::std::os::raw::c_char;
}
unsafe extern "C" {
  pub fn whisper_lang_str_full(id: ::std::os::raw::c_int) -> *const ::std::os::raw::c_char;
}
unsafe extern "C" {
  pub fn whisper_lang_auto_detect(
    ctx: *mut whisper_context,
    offset_ms: ::std::os::raw::c_int,
    n_threads: ::std::os::raw::c_int,
    lang_probs: *mut f32,
  ) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
  pub fn whisper_lang_auto_detect_with_state(
    ctx: *mut whisper_context,
    state: *mut whisper_state,
    offset_ms: ::std::os::raw::c_int,
    n_threads: ::std::os::raw::c_int,
    lang_probs: *mut f32,
  ) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
  pub fn whisper_n_len(ctx: *mut whisper_context) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
  pub fn whisper_n_len_from_state(state: *mut whisper_state) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
  pub fn whisper_n_vocab(ctx: *mut whisper_context) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
  pub fn whisper_n_text_ctx(ctx: *mut whisper_context) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
  pub fn whisper_n_audio_ctx(ctx: *mut whisper_context) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
  pub fn whisper_is_multilingual(ctx: *mut whisper_context) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
  pub fn whisper_model_n_vocab(ctx: *mut whisper_context) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
  pub fn whisper_model_n_audio_ctx(ctx: *mut whisper_context) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
  pub fn whisper_model_n_audio_state(ctx: *mut whisper_context) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
  pub fn whisper_model_n_audio_head(ctx: *mut whisper_context) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
  pub fn whisper_model_n_audio_layer(ctx: *mut whisper_context) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
  pub fn whisper_model_n_text_ctx(ctx: *mut whisper_context) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
  pub fn whisper_model_n_text_state(ctx: *mut whisper_context) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
  pub fn whisper_model_n_text_head(ctx: *mut whisper_context) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
  pub fn whisper_model_n_text_layer(ctx: *mut whisper_context) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
  pub fn whisper_model_n_mels(ctx: *mut whisper_context) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
  pub fn whisper_model_ftype(ctx: *mut whisper_context) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
  pub fn whisper_model_type(ctx: *mut whisper_context) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
  pub fn whisper_get_logits(ctx: *mut whisper_context) -> *mut f32;
}
unsafe extern "C" {
  pub fn whisper_get_logits_from_state(state: *mut whisper_state) -> *mut f32;
}
unsafe extern "C" {
  pub fn whisper_token_to_str(
    ctx: *mut whisper_context,
    token: whisper_token,
  ) -> *const ::std::os::raw::c_char;
}
unsafe extern "C" {
  pub fn whisper_model_type_readable(ctx: *mut whisper_context) -> *const ::std::os::raw::c_char;
}
unsafe extern "C" {
  pub fn whisper_token_eot(ctx: *mut whisper_context) -> whisper_token;
}
unsafe extern "C" {
  pub fn whisper_token_sot(ctx: *mut whisper_context) -> whisper_token;
}
unsafe extern "C" {
  pub fn whisper_token_solm(ctx: *mut whisper_context) -> whisper_token;
}
unsafe extern "C" {
  pub fn whisper_token_prev(ctx: *mut whisper_context) -> whisper_token;
}
unsafe extern "C" {
  pub fn whisper_token_nosp(ctx: *mut whisper_context) -> whisper_token;
}
unsafe extern "C" {
  pub fn whisper_token_not(ctx: *mut whisper_context) -> whisper_token;
}
unsafe extern "C" {
  pub fn whisper_token_beg(ctx: *mut whisper_context) -> whisper_token;
}
unsafe extern "C" {
  pub fn whisper_token_lang(
    ctx: *mut whisper_context,
    lang_id: ::std::os::raw::c_int,
  ) -> whisper_token;
}
unsafe extern "C" {
  pub fn whisper_token_translate(ctx: *mut whisper_context) -> whisper_token;
}
unsafe extern "C" {
  pub fn whisper_token_transcribe(ctx: *mut whisper_context) -> whisper_token;
}
#[repr(C)]
#[derive(Debug, Default, Copy, Clone)]
pub struct whisper_timings {
  pub sample_ms: f32,
  pub encode_ms: f32,
  pub decode_ms: f32,
  pub batchd_ms: f32,
  pub prompt_ms: f32,
}
unsafe extern "C" {
  pub fn whisper_get_timings(ctx: *mut whisper_context) -> *mut whisper_timings;
}
unsafe extern "C" {
  pub fn whisper_print_timings(ctx: *mut whisper_context);
}
unsafe extern "C" {
  pub fn whisper_reset_timings(ctx: *mut whisper_context);
}
unsafe extern "C" {
  pub fn whisper_print_system_info() -> *const ::std::os::raw::c_char;
}
pub const whisper_sampling_strategy_WHISPER_SAMPLING_GREEDY: whisper_sampling_strategy = 0;
pub const whisper_sampling_strategy_WHISPER_SAMPLING_BEAM_SEARCH: whisper_sampling_strategy = 1;
pub type whisper_sampling_strategy = ::std::os::raw::c_uint;
pub type whisper_new_segment_callback = ::std::option::Option<
  unsafe extern "C" fn(
    ctx: *mut whisper_context,
    state: *mut whisper_state,
    n_new: ::std::os::raw::c_int,
    user_data: *mut ::std::os::raw::c_void,
  ),
>;
pub type whisper_progress_callback = ::std::option::Option<
  unsafe extern "C" fn(
    ctx: *mut whisper_context,
    state: *mut whisper_state,
    progress: ::std::os::raw::c_int,
    user_data: *mut ::std::os::raw::c_void,
  ),
>;
pub type whisper_encoder_begin_callback = ::std::option::Option<
  unsafe extern "C" fn(
    ctx: *mut whisper_context,
    state: *mut whisper_state,
    user_data: *mut ::std::os::raw::c_void,
  ) -> bool,
>;
pub type whisper_logits_filter_callback = ::std::option::Option<
  unsafe extern "C" fn(
    ctx: *mut whisper_context,
    state: *mut whisper_state,
    tokens: *const whisper_token_data,
    n_tokens: ::std::os::raw::c_int,
    logits: *mut f32,
    user_data: *mut ::std::os::raw::c_void,
  ),
>;
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct whisper_full_params {
  pub strategy: whisper_sampling_strategy,
  pub n_threads: ::std::os::raw::c_int,
  pub n_max_text_ctx: ::std::os::raw::c_int,
  pub offset_ms: ::std::os::raw::c_int,
  pub duration_ms: ::std::os::raw::c_int,
  pub translate: bool,
  pub no_context: bool,
  pub no_timestamps: bool,
  pub single_segment: bool,
  pub print_special: bool,
  pub print_progress: bool,
  pub print_realtime: bool,
  pub print_timestamps: bool,
  pub token_timestamps: bool,
  pub thold_pt: f32,
  pub thold_ptsum: f32,
  pub max_len: ::std::os::raw::c_int,
  pub split_on_word: bool,
  pub max_tokens: ::std::os::raw::c_int,
  pub debug_mode: bool,
  pub audio_ctx: ::std::os::raw::c_int,
  pub tdrz_enable: bool,
  pub suppress_regex: *const ::std::os::raw::c_char,
  pub initial_prompt: *const ::std::os::raw::c_char,
  pub carry_initial_prompt: bool,
  pub prompt_tokens: *const whisper_token,
  pub prompt_n_tokens: ::std::os::raw::c_int,
  pub language: *const ::std::os::raw::c_char,
  pub detect_language: bool,
  pub suppress_blank: bool,
  pub suppress_nst: bool,
  pub temperature: f32,
  pub max_initial_ts: f32,
  pub length_penalty: f32,
  pub temperature_inc: f32,
  pub entropy_thold: f32,
  pub logprob_thold: f32,
  pub no_speech_thold: f32,
  pub greedy: whisper_full_params__bindgen_ty_1,
  pub beam_search: whisper_full_params__bindgen_ty_2,
  pub new_segment_callback: whisper_new_segment_callback,
  pub new_segment_callback_user_data: *mut ::std::os::raw::c_void,
  pub progress_callback: whisper_progress_callback,
  pub progress_callback_user_data: *mut ::std::os::raw::c_void,
  pub encoder_begin_callback: whisper_encoder_begin_callback,
  pub encoder_begin_callback_user_data: *mut ::std::os::raw::c_void,
  pub abort_callback: ggml_abort_callback,
  pub abort_callback_user_data: *mut ::std::os::raw::c_void,
  pub logits_filter_callback: whisper_logits_filter_callback,
  pub logits_filter_callback_user_data: *mut ::std::os::raw::c_void,
  pub grammar_rules: *mut *const whisper_grammar_element,
  pub n_grammar_rules: usize,
  pub i_start_rule: usize,
  pub grammar_penalty: f32,
  pub vad: bool,
  pub vad_model_path: *const ::std::os::raw::c_char,
  pub vad_params: whisper_vad_params,
}
#[repr(C)]
#[derive(Debug, Default, Copy, Clone)]
pub struct whisper_full_params__bindgen_ty_1 {
  pub best_of: ::std::os::raw::c_int,
}
#[repr(C)]
#[derive(Debug, Default, Copy, Clone)]
pub struct whisper_full_params__bindgen_ty_2 {
  pub beam_size: ::std::os::raw::c_int,
  pub patience: f32,
}
impl Default for whisper_full_params {
  fn default() -> Self {
    let mut s = ::std::mem::MaybeUninit::<Self>::uninit();
    unsafe {
      ::std::ptr::write_bytes(s.as_mut_ptr(), 0, 1);
      s.assume_init()
    }
  }
}
unsafe extern "C" {
  pub fn whisper_context_default_params_by_ref() -> *mut whisper_context_params;
}
unsafe extern "C" {
  pub fn whisper_context_default_params() -> whisper_context_params;
}
unsafe extern "C" {
  pub fn whisper_full_default_params_by_ref(
    strategy: whisper_sampling_strategy,
  ) -> *mut whisper_full_params;
}
unsafe extern "C" {
  pub fn whisper_full_default_params(strategy: whisper_sampling_strategy) -> whisper_full_params;
}
unsafe extern "C" {
  pub fn whisper_full(
    ctx: *mut whisper_context,
    params: whisper_full_params,
    samples: *const f32,
    n_samples: ::std::os::raw::c_int,
  ) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
  pub fn whisper_full_with_state(
    ctx: *mut whisper_context,
    state: *mut whisper_state,
    params: whisper_full_params,
    samples: *const f32,
    n_samples: ::std::os::raw::c_int,
  ) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
  pub fn whisper_full_parallel(
    ctx: *mut whisper_context,
    params: whisper_full_params,
    samples: *const f32,
    n_samples: ::std::os::raw::c_int,
    n_processors: ::std::os::raw::c_int,
  ) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
  pub fn whisper_full_n_segments(ctx: *mut whisper_context) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
  pub fn whisper_full_n_segments_from_state(state: *mut whisper_state) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
  pub fn whisper_full_lang_id(ctx: *mut whisper_context) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
  pub fn whisper_full_lang_id_from_state(state: *mut whisper_state) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
  pub fn whisper_full_get_segment_t0(
    ctx: *mut whisper_context,
    i_segment: ::std::os::raw::c_int,
  ) -> i64;
}
unsafe extern "C" {
  pub fn whisper_full_get_segment_t0_from_state(
    state: *mut whisper_state,
    i_segment: ::std::os::raw::c_int,
  ) -> i64;
}
unsafe extern "C" {
  pub fn whisper_full_get_segment_t1(
    ctx: *mut whisper_context,
    i_segment: ::std::os::raw::c_int,
  ) -> i64;
}
unsafe extern "C" {
  pub fn whisper_full_get_segment_t1_from_state(
    state: *mut whisper_state,
    i_segment: ::std::os::raw::c_int,
  ) -> i64;
}
unsafe extern "C" {
  pub fn whisper_full_get_segment_speaker_turn_next(
    ctx: *mut whisper_context,
    i_segment: ::std::os::raw::c_int,
  ) -> bool;
}
unsafe extern "C" {
  pub fn whisper_full_get_segment_speaker_turn_next_from_state(
    state: *mut whisper_state,
    i_segment: ::std::os::raw::c_int,
  ) -> bool;
}
unsafe extern "C" {
  pub fn whisper_full_get_segment_text(
    ctx: *mut whisper_context,
    i_segment: ::std::os::raw::c_int,
  ) -> *const ::std::os::raw::c_char;
}
unsafe extern "C" {
  pub fn whisper_full_get_segment_text_from_state(
    state: *mut whisper_state,
    i_segment: ::std::os::raw::c_int,
  ) -> *const ::std::os::raw::c_char;
}
unsafe extern "C" {
  pub fn whisper_full_n_tokens(
    ctx: *mut whisper_context,
    i_segment: ::std::os::raw::c_int,
  ) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
  pub fn whisper_full_n_tokens_from_state(
    state: *mut whisper_state,
    i_segment: ::std::os::raw::c_int,
  ) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
  pub fn whisper_full_get_token_text(
    ctx: *mut whisper_context,
    i_segment: ::std::os::raw::c_int,
    i_token: ::std::os::raw::c_int,
  ) -> *const ::std::os::raw::c_char;
}
unsafe extern "C" {
  pub fn whisper_full_get_token_text_from_state(
    ctx: *mut whisper_context,
    state: *mut whisper_state,
    i_segment: ::std::os::raw::c_int,
    i_token: ::std::os::raw::c_int,
  ) -> *const ::std::os::raw::c_char;
}
unsafe extern "C" {
  pub fn whisper_full_get_token_id(
    ctx: *mut whisper_context,
    i_segment: ::std::os::raw::c_int,
    i_token: ::std::os::raw::c_int,
  ) -> whisper_token;
}
unsafe extern "C" {
  pub fn whisper_full_get_token_id_from_state(
    state: *mut whisper_state,
    i_segment: ::std::os::raw::c_int,
    i_token: ::std::os::raw::c_int,
  ) -> whisper_token;
}
unsafe extern "C" {
  pub fn whisper_full_get_token_data(
    ctx: *mut whisper_context,
    i_segment: ::std::os::raw::c_int,
    i_token: ::std::os::raw::c_int,
  ) -> whisper_token_data;
}
unsafe extern "C" {
  pub fn whisper_full_get_token_data_from_state(
    state: *mut whisper_state,
    i_segment: ::std::os::raw::c_int,
    i_token: ::std::os::raw::c_int,
  ) -> whisper_token_data;
}
unsafe extern "C" {
  pub fn whisper_full_get_token_p(
    ctx: *mut whisper_context,
    i_segment: ::std::os::raw::c_int,
    i_token: ::std::os::raw::c_int,
  ) -> f32;
}
unsafe extern "C" {
  pub fn whisper_full_get_token_p_from_state(
    state: *mut whisper_state,
    i_segment: ::std::os::raw::c_int,
    i_token: ::std::os::raw::c_int,
  ) -> f32;
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct whisper_vad_context {
  _unused: [u8; 0],
}
unsafe extern "C" {
  pub fn whisper_vad_default_params() -> whisper_vad_params;
}
#[repr(C)]
#[derive(Debug, Default, Copy, Clone)]
pub struct whisper_vad_context_params {
  pub n_threads: ::std::os::raw::c_int,
  pub use_gpu: bool,
  pub gpu_device: ::std::os::raw::c_int,
}
unsafe extern "C" {
  pub fn whisper_vad_default_context_params() -> whisper_vad_context_params;
}
unsafe extern "C" {
  pub fn whisper_vad_init_from_file_with_params(
    path_model: *const ::std::os::raw::c_char,
    params: whisper_vad_context_params,
  ) -> *mut whisper_vad_context;
}
unsafe extern "C" {
  pub fn whisper_vad_init_with_params(
    loader: *mut whisper_model_loader,
    params: whisper_vad_context_params,
  ) -> *mut whisper_vad_context;
}
unsafe extern "C" {
  pub fn whisper_vad_detect_speech(
    vctx: *mut whisper_vad_context,
    samples: *const f32,
    n_samples: ::std::os::raw::c_int,
  ) -> bool;
}
unsafe extern "C" {
  pub fn whisper_vad_n_probs(vctx: *mut whisper_vad_context) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
  pub fn whisper_vad_probs(vctx: *mut whisper_vad_context) -> *mut f32;
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct whisper_vad_segments {
  _unused: [u8; 0],
}
unsafe extern "C" {
  pub fn whisper_vad_segments_from_probs(
    vctx: *mut whisper_vad_context,
    params: whisper_vad_params,
  ) -> *mut whisper_vad_segments;
}
unsafe extern "C" {
  pub fn whisper_vad_segments_from_samples(
    vctx: *mut whisper_vad_context,
    params: whisper_vad_params,
    samples: *const f32,
    n_samples: ::std::os::raw::c_int,
  ) -> *mut whisper_vad_segments;
}
unsafe extern "C" {
  pub fn whisper_vad_segments_n_segments(
    segments: *mut whisper_vad_segments,
  ) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
  pub fn whisper_vad_segments_get_segment_t0(
    segments: *mut whisper_vad_segments,
    i_segment: ::std::os::raw::c_int,
  ) -> f32;
}
unsafe extern "C" {
  pub fn whisper_vad_segments_get_segment_t1(
    segments: *mut whisper_vad_segments,
    i_segment: ::std::os::raw::c_int,
  ) -> f32;
}
unsafe extern "C" {
  pub fn whisper_vad_free_segments(segments: *mut whisper_vad_segments);
}
unsafe extern "C" {
  pub fn whisper_vad_free(ctx: *mut whisper_vad_context);
}
unsafe extern "C" {
  pub fn whisper_bench_memcpy(n_threads: ::std::os::raw::c_int) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
  pub fn whisper_bench_memcpy_str(
    n_threads: ::std::os::raw::c_int,
  ) -> *const ::std::os::raw::c_char;
}
unsafe extern "C" {
  pub fn whisper_bench_ggml_mul_mat(n_threads: ::std::os::raw::c_int) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
  pub fn whisper_bench_ggml_mul_mat_str(
    n_threads: ::std::os::raw::c_int,
  ) -> *const ::std::os::raw::c_char;
}
unsafe extern "C" {
  pub fn whisper_log_set(log_callback: ggml_log_callback, user_data: *mut ::std::os::raw::c_void);
}
unsafe extern "C" {
  pub fn whisper_full_get_segment_no_speech_prob(
    ctx: *mut whisper_context,
    i_segment: ::std::os::raw::c_int,
  ) -> f32;
}
unsafe extern "C" {
  pub fn whisper_full_get_segment_no_speech_prob_from_state(
    state: *mut whisper_state,
    i_segment: ::std::os::raw::c_int,
  ) -> f32;
}
#[repr(C)]
#[derive(Debug, Default, Copy, Clone)]
pub struct ggml_backend_buffer {
  pub _address: u8,
}
